### ISSUE TITLE
Missing alt attribute

### ISSUE THREAD

**Issue by macure** [urlbox/wordpress-screenshots#3]
We have no way of setting an alt attribute for the rendered images. Which makes Google Lighthouse and SEO tools  complain.

Can you consider adding alt parameter to the short-code please?

**Comment by jot** [comment]
Hi @macure. Thank you for raising this. We'd be happy to review and merge a pull request to address this. Please email support@urlbox.com if you create one and we'll prioritise a review.

**Comment by AJCJ1** [comment]
Hey @macure. The above issue has been resolved, and you can now add an alt tag as of v1.5.3.
