### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by macure** [urlbox/wordpress-screenshots#4]
We have a lot of forbidden access screenshots, simply because the requests that your service makes is from a country that is not allowed to visit the site. In the documentation I can see that it is possible to set a proxy when using a library, but I can not see that this is the same for the Wordpress Plug-in.

Can you consider adding that feature?

**Comment by jot** [comment]
Hi @macure. Thank you for raising this. We'd be happy to review and merge a pull request to address this. Please email support@urlbox.com if you create one and we'll prioritise a review.

**Comment by AJCJ1** [comment]
Urlbox's screenshot plugin now allows proxies to be used as of V1.6.0.

With the latest update, you should be able to enter your proxies' details in the plugin settings page and get using it right away.

Please let us know of any issues you encounter and we will do our best to support.

In case you need a quick guide on using proxies with Urlbox, take a look at our [guide](https://urlbox.com/docs/guides/proxies), which includes some suggestions for proxy providers.
